-- ==========================================
-- 追加テーブル移行用SQL
-- black_posts と pomodoro_sessions
-- ==========================================

-- ==========================================
-- 1. black_posts (BlackLens 投稿)
-- ==========================================
CREATE TABLE IF NOT EXISTS black_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nickname TEXT NOT NULL DEFAULT '名無し',
    content TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT 'なんでも',
    wakaru_count INTEGER NOT NULL DEFAULT 0,
    yell_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS: 誰でも読み取り・書き込み可能（匿名掲示板のため）
ALTER TABLE black_posts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public access for black_posts" ON black_posts FOR ALL USING (true) WITH CHECK (true);


-- ==========================================
-- 2. pomodoro_sessions (EduTimer履歴)
-- ==========================================
CREATE TABLE IF NOT EXISTS pomodoro_sessions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL, -- auth.usersへの参照
    session_count INTEGER NOT NULL DEFAULT 1,
    work_duration INTEGER NOT NULL, -- 分単位
    completed_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW() -- CSVに含まれていたため追加
);

-- RLS: ユーザーは自分のセッションのみアクセス可能
ALTER TABLE pomodoro_sessions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own sessions" 
ON pomodoro_sessions FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own sessions" 
ON pomodoro_sessions FOR INSERT 
WITH CHECK (auth.uid() = user_id);
