-- ===========================================
-- EduLens for School データベーススキーマ
-- 既存Mistapプロジェクトへの追加用（修正版）
-- ===========================================

-- Enum型の作成（存在しない場合のみ）
DO $$ BEGIN
    CREATE TYPE submission_status AS ENUM ('none', 'done', 'forgot', 'incomplete');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE task_type AS ENUM ('print', 'report', 'work', 'other');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- ===========================================
-- テーブル作成
-- ===========================================

-- 塾（学習塾）
CREATE TABLE IF NOT EXISTS cram_schools (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 教科
CREATE TABLE IF NOT EXISTS subjects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ===========================================
-- 既存profilesテーブルにカラム追加
-- ===========================================

-- login_id カラム追加（EduLens School用ログインID）
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'profiles' AND column_name = 'login_id') THEN
        ALTER TABLE profiles ADD COLUMN login_id TEXT UNIQUE;
    END IF;
END $$;

-- cram_school_id カラム追加（所属塾）
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'profiles' AND column_name = 'cram_school_id') THEN
        ALTER TABLE profiles ADD COLUMN cram_school_id UUID REFERENCES cram_schools(id);
    END IF;
END $$;

-- school_name カラム追加（学校名）
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'profiles' AND column_name = 'school_name') THEN
        ALTER TABLE profiles ADD COLUMN school_name TEXT;
    END IF;
END $$;

-- ===========================================
-- 新規テーブル作成
-- ===========================================

-- 日々の記録
CREATE TABLE IF NOT EXISTS daily_logs (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  student_id UUID REFERENCES profiles(id) NOT NULL,
  subject_id BIGINT REFERENCES subjects(id) NOT NULL,
  date DATE DEFAULT CURRENT_DATE,
  hand_raised_count INT DEFAULT 0,
  submission_status submission_status DEFAULT 'none',
  attitude_score INT CHECK (attitude_score >= 1 AND attitude_score <= 5),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ワーク（問題集）
CREATE TABLE IF NOT EXISTS workbooks (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  cram_school_id UUID REFERENCES cram_schools(id),
  student_id UUID REFERENCES profiles(id),
  subject_id BIGINT REFERENCES subjects(id),
  title TEXT NOT NULL,
  current_page INT DEFAULT 0,
  target_page INT DEFAULT 0,
  deadline DATE,
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 単発タスク（宿題）
CREATE TABLE IF NOT EXISTS one_off_tasks (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  student_id UUID REFERENCES profiles(id) NOT NULL,
  subject_id BIGINT REFERENCES subjects(id),
  task_type task_type DEFAULT 'print',
  title TEXT,
  deadline DATE,
  is_completed BOOLEAN DEFAULT FALSE,
  image_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ===========================================
-- インデックス
-- ===========================================

CREATE INDEX IF NOT EXISTS idx_profiles_login_id ON profiles(login_id);
CREATE INDEX IF NOT EXISTS idx_profiles_cram_school_id ON profiles(cram_school_id);
CREATE INDEX IF NOT EXISTS idx_daily_logs_student_id ON daily_logs(student_id);
CREATE INDEX IF NOT EXISTS idx_daily_logs_date ON daily_logs(date);
CREATE INDEX IF NOT EXISTS idx_workbooks_student_id ON workbooks(student_id);
CREATE INDEX IF NOT EXISTS idx_one_off_tasks_student_id ON one_off_tasks(student_id);
CREATE INDEX IF NOT EXISTS idx_one_off_tasks_is_completed ON one_off_tasks(is_completed);

-- ===========================================
-- Row Level Security (RLS)
-- ===========================================

ALTER TABLE daily_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE workbooks ENABLE ROW LEVEL SECURITY;
ALTER TABLE one_off_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE cram_schools ENABLE ROW LEVEL SECURITY;

-- 日々の記録
DROP POLICY IF EXISTS "Students can manage own logs" ON daily_logs;
CREATE POLICY "Students can manage own logs" ON daily_logs
  FOR ALL USING (auth.uid() = student_id);

DROP POLICY IF EXISTS "Teachers can view student logs" ON daily_logs;
CREATE POLICY "Teachers can view student logs" ON daily_logs
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM profiles p
      WHERE p.id = auth.uid() AND p.role = 'teacher'::text
    )
  );

-- ワーク
DROP POLICY IF EXISTS "Students can manage own workbooks" ON workbooks;
CREATE POLICY "Students can manage own workbooks" ON workbooks
  FOR ALL USING (auth.uid() = student_id);

DROP POLICY IF EXISTS "Teachers can manage workbooks" ON workbooks;
CREATE POLICY "Teachers can manage workbooks" ON workbooks
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM profiles p
      WHERE p.id = auth.uid() AND p.role = 'teacher'::text
    )
  );

-- 単発タスク
DROP POLICY IF EXISTS "Students can manage own tasks" ON one_off_tasks;
CREATE POLICY "Students can manage own tasks" ON one_off_tasks
  FOR ALL USING (auth.uid() = student_id);

DROP POLICY IF EXISTS "Teachers can view student tasks" ON one_off_tasks;
CREATE POLICY "Teachers can view student tasks" ON one_off_tasks
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM profiles p
      WHERE p.id = auth.uid() AND p.role = 'teacher'::text
    )
  );

-- 教科・塾: 全員閲覧可能
DROP POLICY IF EXISTS "Everyone can view subjects" ON subjects;
CREATE POLICY "Everyone can view subjects" ON subjects
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Everyone can view cram schools" ON cram_schools;
CREATE POLICY "Everyone can view cram schools" ON cram_schools
  FOR SELECT USING (true);

-- ===========================================
-- 初期データ（教科マスタ）
-- ===========================================

INSERT INTO subjects (name) 
SELECT name FROM (VALUES 
  ('国語'),
  ('数学'),
  ('英語'),
  ('理科'),
  ('社会'),
  ('音楽'),
  ('美術'),
  ('体育'),
  ('技術'),
  ('家庭'),
  ('プログラミング')
) AS t(name)
WHERE NOT EXISTS (SELECT 1 FROM subjects WHERE subjects.name = t.name);

-- サンプル塾（テスト用）
INSERT INTO cram_schools (name)
SELECT 'EduLens学習塾 本校'
WHERE NOT EXISTS (SELECT 1 FROM cram_schools WHERE name = 'EduLens学習塾 本校');
